networks:
  frontend_net:
  postgres_net:

volumes:
  secure-note_postgres_data:

services:

  postgres:
    container_name: ${POSTGRES_HOST}
    image: postgres:18.3
    command: [ "postgres", "-p", "${POSTGRES_PORT}" ]
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    env_file:
      - security_postgres.env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - secure-note_postgres_data:/var/lib/postgresql
    networks:
      - postgres_net
    restart: unless-stopped

  backend:
    container_name: ${BACKEND_HOST}
    image: secure-note-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    env_file:
      - security_postgres.env
      - security_jwt.env
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      SERVER_PORT: ${BACKEND_PORT}
    networks:
      - frontend_net
      - postgres_net
    depends_on:
      - postgres
    restart: unless-stopped

  frontend:
    container_name: ${FRONTEND_HOST}
    image: secure-note-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    environment:
      REACT_APP_BACKEND_HOST: ${BACKEND_HOST}
      REACT_APP_BACKEND_PORT: ${BACKEND_PORT}
    networks:
      - frontend_net
    restart: unless-stopped