ember {
host = localhost
host = ${?SERVER_HOST}

port = 8080
port = ${?SERVER_PORT}
}



jwt {
  expiration = 11800
}

db-host = "localhost"
db-host = ${?POSTGRES_HOST}

db-port = "5432"
db-port = ${?POSTGRES_PORT}

db-name = "postgres"
db-name = ${?POSTGRES_DB}

database {
  driver = "org.postgresql.Driver"

  url = "jdbc:postgresql://"${db-host}":"${db-port}"/"${db-name}

  user = "admin"
  user = ${?POSTGRES_USER}
}

include "secrets.conf"
